approvedGitRepositories:
  - '**'

enableGlobalCache: false
enableImmutableInstalls: false
enableScripts: true
globalFolder: .yarn/berry
ignorePath: true
networkConcurrency: 16
nodeLinker: pnp
npmMinimalAgeGate: 0
npmPreapprovedPackages:
  - '@ioterax/*'
npmAuditRegistry: 'https://registry.npmjs.org'
npmPublishRegistry: 'https://npm.pkg.github.com'
npmRegistryServer: 'https://registry.npmjs.org'
npmScopes:
  ioterax:
    npmRegistryServer: 'https://npm.pkg.github.com'
    npmAlwaysAuth: true
    npmAuthToken: '${NODE_AUTH_TOKEN:-}'
logFilters:
  - pattern: 'prom-client is listed by your project with version 0.16.0*'
    level: discard
  - code: YN0086
    level: discard
pnpMode: strict
pnpUnpluggedFolder: .yarn/unplugged
yarnPath: .yarn/releases/yarn-4.18.0.cjs
