apiVersion: v1 
kind: Service 
metadata: 
  name: backend-microservices
  namespace: laniakea-central
spec: 
  selector: 
    app: mcs-central
  type: NodePort 
  ports: 
    - name: http 
      port: 3000
      nodePort: 30080