import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { HydratedDocument } from 'mongoose';
import { ICountry } from '@ioterax/laniakea-lib-central';

/**
 * This type represents a Mongoose document for the `Country` class.
 */
export type CountryDocumentType = HydratedDocument<Country>;

/**
 * The `Country` class represents a country entity within the application.
 * It implements the {@link ICountry} interface and is decorated with the Mongoose schema decorator.
 * This schema defines the structure of the `countries` collection in MongoDB.
 *
 * For more details on the `ICountry` interface, see the {@link ICountry} documentation.
 */
@Schema({ collection: 'countries' })
export class Country implements ICountry {
  /**
   * The unique identifier of the country document.
   * This field is automatically generated by MongoDB.
   */
  id: string;

  /**
   * The numeric code of the country.
   * This field is required, indexed, and must be unique.
   */
  @Prop({ required: true, index: true, unique: true })
  code: number;

  /**
   * The name of the country.
   * This field is required, indexed, and must be unique.
   */
  @Prop({ required: true, index: true, unique: true })
  name: string;

  /**
   * The Mobile Country Code (MCC) of the country.
   * This field is required, indexed, and must be unique.
   */
  @Prop({ required: false, index: false, unique: false })
  mcc: number;

  /**
   * The initials of the country (e.g., 'US' for United States).
   * This field is required and indexed.
   */
  @Prop({ required: true, index: true })
  initials: string;

  /**
   * The primary language spoken in the country.
   * This field is required.
   */
  @Prop({ required: true })
  language: string;

  /**
   * The date and time when the country document was created.
   * This field is required, indexed, and must be unique.
   */
  @Prop({ required: true, index: true, unique: true })
  createdAt: Date;

  /**
   * The date and time when the country document was last modified.
   * This field is required, indexed, and must be unique.
   */
  @Prop({ required: true, index: true, unique: true })
  updatedAt: Date;

  @Prop({ type: Date, required: false, default: null })
  revokedAt?: Date | null | undefined;

  /**
   * A digital signature to ensure the integrity of the country document.
   * This field is required.
   */
  @Prop({ required: true })
  signature: string;

  @Prop({ required: false })
  isoCode: string;

  @Prop({ required: false })
  isoNumeric: number;
}

/**
 * The Mongoose schema for the `Country` class.
 * This schema is generated using the `SchemaFactory` and defines how the `Country` documents will be stored in the database.
 */
export const CountrySchema = SchemaFactory.createForClass(Country);

// CountrySchema.index({});
