import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { HydratedDocument } from 'mongoose';
import { ICountry } from '@ioterax/foundation-lib-central';
import { applyDefaultTransform } from '@ioterax/infra-lib-database';

/**
 * The `Country` class represents a country entity within the application.
 * It implements the {@link ICountry} interface and is decorated with the Mongoose schema decorator.
 * This schema defines the structure of the `countries` collection in MongoDB.
 *
 * For more details on the `ICountry` interface, see the {@link ICountry} documentation.
 */
@Schema({ collection: 'countries' })
export class Country implements ICountry {
  /**
   * The unique identifier of the country document.
   * This field is automatically generated by MongoDB.
   */
  id!: string;

  /**
   * The numeric code of the country.
   * This field is required, indexed, and must be unique.
   */
  @Prop({ required: true, index: true, unique: true })
  code!: number;

  /**
   * The name of the country.
   * This field is required, indexed, and must be unique.
   */
  @Prop({ required: true, index: true, unique: true })
  name!: string;

  /**
   * The Mobile Country Code (MCC) of the country.
   * This field is required, indexed, and must be unique.
   */
  @Prop({ required: false, index: false, unique: false })
  mcc!: number;

  /**
   * The initials of the country (e.g., 'US' for United States).
   * This field is required and indexed.
   */
  @Prop({ required: true, index: true })
  initials!: string;

  /**
   * The primary language spoken in the country.
   * This field is required.
   */
  @Prop({ required: true })
  language!: string;

  @Prop({ required: false })
  isoCode!: string;

  @Prop({ required: false })
  isoNumeric!: number;

  @Prop({ type: Date, required: true, default: () => new Date() })
  createdAt!: Date;

  @Prop({ type: Date, required: true, default: () => new Date() })
  updatedAt!: Date;

  @Prop({ type: Date, required: false, default: null })
  revokedAt?: Date | null;

  /**
   * @property {string} signature - Unique signature hash for the client.
   */
  @Prop({ required: true })
  signature!: string;
}

export type CountryDocumentType = HydratedDocument<Country>;
export const CountrySchema = SchemaFactory.createForClass(Country);
applyDefaultTransform(CountrySchema);

//TODO: CREATE INDEXES IF NEEDED
